name: Shippie 🚢

on:
  pull_request:
    branches: [main]

permissions:
  pull-requests: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

              # 3. Configurar Bun
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Shippie 🚢
        run: npm install mattzcarey/shippie@v0.14.2
        
        with:
          GITHUB_TOKEN: ${{ github.token }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MODEL_STRING: "openai:gpt-4o"
          BASE_URL: "https://models.inference.ai.azure.com"
          REVIEW_LANGUAGE: "spanish"


      - name: Install and Run Shippie 🚢
        shell: bash
        run: |
          bun add shippie@latest
          bun shippie --debug=$DEBUG review --platform=github --modelString=$MODEL_STRING --reviewLanguage=$REVIEW_LANGUAGE --maxSteps=$MAX_STEPS --baseUrl=$BASE_URL --telemetry=$TELEMETRY
