name: Shippie 🚢

on:
  pull_request:
    branches: [main]

permissions:
  pull-requests: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all history and PR base
        run: |
          git fetch origin +refs/heads/*:refs/remotes/origin/*

      - name: Clone shippie tool
        run: git clone https://github.com/jhovannycanas/shippie.git shippie-tool

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install shippie dependencies
        run: |
          cd shippie-tool
          bun install

      - name: Run shippie review on PR code
        run: |
          bun run ./shippie-tool/src/index.ts review \
            --platform=github \
            --modelString=openai:gpt-4o \
            --baseUrl=https://models.inference.ai.azure.com \
            --reviewLanguage=es \
            --maxSteps=10
        env:
          GITHUB_TOKEN: ${{ github.token }}
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_SHA: ${{ github.sha }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
