name: Shippie 🚢

on:
  pull_request:
    branches: [main]

permissions:
  pull-requests: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4

      # Descargar la herramienta externa
      - name: Clone shippie tool
        run: git clone https://github.com/jhovannycanas/shippie.git shippie-tool

      # 3. Configurar Bun
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest


      # Instalar dependencias de la herramienta externa
      - name: Install shippie dependencies
        run: |
          cd shippie-tool
          bun install

      # Ejecutar la herramienta sobre el código que acaba de hacer checkout el workflow (la raíz)
      - name: Run shippie review
        run: |
          cd shippie-tool
          bun run ./src/index.ts review --platform=github --modelString=openai:gpt-4o --baseUrl=https://models.inference.ai.azure.com --reviewLanguage=es --maxSteps=10 --repoPath=../    # repoPath apunta al código de la PR

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_SHA: ${{ github.event.pull_request.base.sha || github.repository.default_branch || 'main' }}
          GITHUB_SHA: ${{ github.sha }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
